version: "3.8"
services:
  redmine:
    image: redmine
    restart: always
    ports:
      -80:3000
    volumes:
      -  /home/glesio/workspace/docker/var/redmine/files:/usr/src/redmine/files
      -  /home/glesio/workspace/docker/var/redmine/plugins:/usr/src/redmine/plugins
      -  /home/glesio/workspace/docker/var/redmine/vendor/plugins:/usr/src/redmine/vendor/plugins
      -  /home/glesio/workspace/docker/var/redmine/public/themes:/usr/src/redmine/public/themes
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: 102030
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_ENCODING: utf8
    depends_on:
      - pgServer
  pgServer:
    image:
      postgres:latest
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
    volumes:
      - /home/glesio/workspace/docker/database/:/var/lib/postgresql/dat  